"""`delegate docs` also writes `includes/abbreviations.md` from `docs/glossary.md`, and checks that the committed file is current.

The site appends that file to every page, so each term of the glossary shows its
definition as a tooltip. The glossary is the one source. The cases run on a copy
of the pages, so the repository stays as it is.
"""

import shutil

import pytest

from agent_definitions import delegate

from .pages import ROOT, outside_the_package

HEADER = "<!-- Generated by `delegate docs` from docs/glossary.md. Do not edit this file by hand. -->"
FILE = "includes/abbreviations.md"

GLOSSARY = """# Glossary

This page explains the terms that the docs use.

## ACCEPT

ACCEPT is the verdict that a verifier gives when the work does what the ticket asks. Only an ACCEPT moves the run branch. See [the verifier step](reference/run.md#the-verifier-step).

## `assure`

`assure` is the mode that verifies each ticket branch at once,
before the next ticket builds on it. It costs more than `economy`.

## Agent pair

An agent pair is a specialist and its verifier. See [why](explanation/why-each-specialist-has-a-twin.md).

Not: pair, specialist-verifier pair.
"""


@pytest.fixture
def pages(tmp_path):
    """A copy of the pages that `delegate docs` writes, without a glossary."""
    shutil.copytree(ROOT / "docs", tmp_path / "docs")
    (tmp_path / "docs" / "glossary.md").unlink(missing_ok=True)
    skill = tmp_path / "skills" / "agent-definitions" / "SKILL.md"
    skill.parent.mkdir(parents=True)
    shutil.copy(ROOT / "skills" / "agent-definitions" / "SKILL.md", skill)
    return tmp_path


def docs(capsys, *argv):
    code = delegate.main(["docs", *argv])
    out, err = capsys.readouterr()
    return code, out, err


@outside_the_package
def test_each_term_of_the_glossary_becomes_one_abbreviation_with_its_first_sentence_as_plain_text(pages, capsys):
    (pages / "docs" / "glossary.md").write_text(GLOSSARY)

    code, out, err = docs(capsys, "--root", str(pages))

    assert (code, err) == (0, "")
    assert f"updated {FILE}" in out
    assert (pages / FILE).read_text() == (
        f"{HEADER}\n\n"
        "*[ACCEPT]: ACCEPT is the verdict that a verifier gives when the work does what the ticket asks.\n"
        "*[assure]: assure is the mode that verifies each ticket branch at once, before the next ticket builds on it.\n"
        "*[Agent pair]: An agent pair is a specialist and its verifier.\n"
    )


@outside_the_package
def test_a_root_with_no_glossary_gets_an_abbreviations_file_that_holds_only_the_header(pages, capsys):
    code, out, err = docs(capsys, "--root", str(pages))

    assert (code, err) == (0, "")
    assert (pages / FILE).read_text() == f"{HEADER}\n"
    assert docs(capsys, "--root", str(pages), "--check")[0] == 0


@outside_the_package
def test_the_check_fails_and_names_the_file_when_the_glossary_changed_after_the_file_was_written(pages, capsys):
    glossary = pages / "docs" / "glossary.md"
    glossary.write_text(GLOSSARY)
    docs(capsys, "--root", str(pages))
    glossary.write_text(GLOSSARY.replace("verdict that a verifier gives", "verdict that a reviewer gives"))
    committed = (pages / FILE).read_text()

    code, out, err = docs(capsys, "--root", str(pages), "--check")

    assert code == 1
    assert FILE in err and "docs/glossary.md" in err
    assert (pages / FILE).read_text() == committed  # the check writes nothing


@outside_the_package
def test_the_check_fails_when_the_file_is_missing_and_the_next_write_restores_it(pages, capsys):
    (pages / "docs" / "glossary.md").write_text(GLOSSARY)
    docs(capsys, "--root", str(pages))
    (pages / FILE).unlink()

    code, out, err = docs(capsys, "--root", str(pages), "--check")
    assert code == 1 and FILE in err

    assert docs(capsys, "--root", str(pages))[0] == 0
    assert docs(capsys, "--root", str(pages), "--check")[0] == 0


@outside_the_package
def test_the_check_fails_when_someone_edits_the_abbreviations_file_by_hand(pages, capsys):
    (pages / "docs" / "glossary.md").write_text(GLOSSARY)
    docs(capsys, "--root", str(pages))
    path = pages / FILE
    path.write_text(path.read_text() + "*[Extra]: A term that the glossary does not hold.\n")

    code, out, err = docs(capsys, "--root", str(pages), "--check")

    assert code == 1 and FILE in err


@outside_the_package
def test_an_entry_with_no_text_is_an_error_that_names_the_term(pages, capsys):
    (pages / "docs" / "glossary.md").write_text("# Glossary\n\n## Empty term\n\n## Next\n\nNext is a term.\n")

    code, out, err = docs(capsys, "--root", str(pages))

    assert code == 2
    assert "Empty term" in err and "docs/glossary.md" in err
    assert not (pages / FILE).exists()


@outside_the_package
def test_a_term_that_appears_twice_is_an_error_that_names_the_term(pages, capsys):
    (pages / "docs" / "glossary.md").write_text("# Glossary\n\n## Run\n\nA run is one pass.\n\n## Run\n\nA run is another pass.\n")

    code, out, err = docs(capsys, "--root", str(pages))

    assert code == 2
    assert "Run" in err and "twice" in err


@outside_the_package
def test_the_committed_abbreviations_file_matches_the_committed_glossary():
    """The drift test of the file. A change of `docs/glossary.md` with no `delegate docs` fails it."""
    assert delegate.main(["docs", "--check", "--root", str(ROOT)]) == 0, "run `delegate docs` and commit the result"
    assert (ROOT / FILE).is_file()
