"""`delegate docs`: write the generated sections of the reference pages, or check that they are current.

A page holds hand-written prose and generated sections. A generated section sits
between two markers:

    <!-- generated:begin <id> -->
    ...
    <!-- generated:end <id> -->

The command replaces the text between the markers with text that it builds from
the code (the argument parsers, the exit-code table, the renderer constants and
the finding codes), so a page cannot drift from the code. Hand-written prose
outside the markers is never touched. A section with no marker in its page is an
error, and so is a missing page: the command never adds a section to a page.
"""

from __future__ import annotations

import argparse
import re
import sys
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path

from . import brief, cli, render, run, status, validate, watch

NOTICE: str = "<!-- Generated by `delegate docs`. Do not edit this section by hand. -->"

RUN_PAGE: str = "docs/reference/run.md"
STATUS_PAGE: str = "docs/reference/status-and-watch.md"
COMMANDS_PAGE: str = "docs/reference/commands.md"
SKILL_PAGE: str = "skills/agent-definitions/SKILL.md"
DOCS_PAGE: str = "docs/reference/docs.md"


class DocsError(Exception):
    """A page is missing, or a page has no valid marker for a section. The message names the page and the section."""


@dataclass(frozen=True)
class Section:
    """One generated section: the page that holds it (relative to the root), its id, what it is built from, and the function that builds its text."""

    page: str
    id: str
    source: str
    build: Callable[[], str]

    @property
    def name(self) -> str:
        return f"{self.page}:{self.id}"


def _value_name(action: argparse.Action) -> str:
    if action.choices:
        return "|".join(str(choice) for choice in action.choices)
    return "<" + (action.metavar or action.dest).lower().replace("_", "-") + ">"  # type: ignore[union-attr]


def _invocation(action: argparse.Action) -> str:
    """The way a reader writes the argument: `--repo <repo>`, `--dry-run`, or `[<run-id>]`."""
    if not action.option_strings:
        name = _value_name(action)
        return f"[{name}]" if action.nargs in ("?", "*") else name
    flags = ", ".join(action.option_strings)
    return flags if action.nargs == 0 else f"{flags} {_value_name(action)}"


def _sentence(text: str) -> str:
    text = text[0].upper() + text[1:]
    return text if text.endswith((".", "!", "?")) else text + "."


def options_table(parser: argparse.ArgumentParser) -> str:
    """A table of the options and the positional arguments of a parser, with the help text of each, in parser order."""
    rows = ["| Option | Meaning |", "|---|---|"]
    # `_actions` is the only way argparse lists the arguments of a parser.
    for action in parser._actions:  # noqa: SLF001
        if action.dest == "help" or isinstance(action.choices, dict):  # -h, and the action of the subcommands
            continue
        if action.help is None:
            raise DocsError(f"argument {_invocation(action)} of {parser.prog} has no help text")
        meaning = _sentence(action.help.replace("|", "\\|").replace("<", "\\<"))  # a bare `<name>` would be read as a tag
        if action.required or (not action.option_strings and action.nargs not in ("?", "*")):
            meaning += " Required."
        rows.append(f"| `{_invocation(action)}` | {meaning} |")
    return "\n".join(rows)


def _subparser(parser: argparse.ArgumentParser, name: str) -> argparse.ArgumentParser:
    """The parser of the subcommand `name`. Raise DocsError when the parser has no such subcommand."""
    for action in parser._actions:  # noqa: SLF001
        if isinstance(action.choices, dict) and name in action.choices:
            return action.choices[name]
    raise DocsError(f"{parser.prog} has no subcommand {name!r}")


def exit_code_table(reasons: dict[int, str], conditions: dict[int, str]) -> str:
    """A table of exit codes with the reason and the condition of each. A code with no condition is an error."""
    if reasons.keys() != conditions.keys():
        raise DocsError(f"the exit codes {sorted(reasons)} and the exit-code conditions {sorted(conditions)} differ")
    rows = ["| Code | Reason | When |", "|---|---|---|"]
    rows += [f"| {code} | {reasons[code]} | {conditions[code]} |" for code in sorted(reasons)]
    return "\n".join(rows)


def _commands(commands: tuple[str, ...] | list[str]) -> str:
    return ", ".join(f"`{command}`" for command in commands)


def guard_table() -> str:
    """The table of the commands that the verifier guard permits, from the constants of the renderer."""
    git_reads = [c for c in render.VERIFIER_READ_COMMANDS if c.startswith("git ")]
    shell_reads = [c for c in render.VERIFIER_READ_COMMANDS if not c.startswith("git ")]
    prefixes = list(render.VERIFIER_TEMP_PATH_PREFIXES)
    temp_paths = ", ".join(f"`{p}`" for p in prefixes[:-1]) + f", or `{prefixes[-1]}`"
    return "\n".join([
        "| Group | Commands |",
        "|---|---|",
        f"| git reads | {_commands(git_reads)} |",
        f"| shell reads | {_commands(shell_reads)} |",
        f"| temp writes | {_commands(render.VERIFIER_TEMP_WRITE_COMMANDS)} — each one only when every path argument starts with {temp_paths}. "
        "A redirection target obeys the same rule, in every segment. |",
        f"| temp destination | {_commands(render.VERIFIER_TEMP_DEST_COMMANDS)} — each one only when the last path argument is a temp path. "
        "The earlier path arguments are sources, and a read of any path is a read. |",
    ])


def finding_code_table() -> str:
    """The table of the finding codes of the validator, from `FINDING_CODES`."""
    rows = ["| Code | Meaning |", "|---|---|"]
    rows += [f"| `{code}` | {meaning} |" for code, meaning in validate.FINDING_CODES.items()]
    return "\n".join(rows)


def generated_sections_table() -> str:
    """The table of every generated section: its page, its id, and what the code builds it from."""
    rows = ["| Page | Section | Built from |", "|---|---|---|"]
    rows += [f"| `{section.page}` | `{section.id}` | {section.source} |" for section in SECTIONS]
    return "\n".join(rows)


SECTIONS: tuple[Section, ...] = (
    Section(RUN_PAGE, "run-options", "The argument parser of `delegate run`.", lambda: options_table(run.build_parser())),
    Section(
        STATUS_PAGE, "status-options", "The argument parser of `delegate status`.", lambda: options_table(status.build_parser())
    ),
    Section(STATUS_PAGE, "watch-options", "The argument parser of `delegate watch`.", lambda: options_table(watch.build_parser())),
    Section(
        STATUS_PAGE, "watch-exit-codes", "The exit codes of `delegate watch`.",
        lambda: exit_code_table(watch.EXIT_CODES, watch.EXIT_CODE_CONDITIONS),
    ),
    Section(
        COMMANDS_PAGE, "agent-definitions-options", "The options of `agent-definitions` before its subcommand.",
        lambda: options_table(cli.build_parser()),
    ),
    Section(
        COMMANDS_PAGE, "render-options", "The `render` parser of `agent-definitions`.",
        lambda: options_table(_subparser(cli.build_parser(), "render")),
    ),
    Section(
        COMMANDS_PAGE, "validate-options", "The `validate` parser of `agent-definitions`.",
        lambda: options_table(_subparser(cli.build_parser(), "validate")),
    ),
    Section(
        COMMANDS_PAGE, "bootstrap-options", "The `bootstrap` parser of `agent-definitions`.",
        lambda: options_table(_subparser(cli.build_parser(), "bootstrap")),
    ),
    Section(
        COMMANDS_PAGE, "brief-full-options", "The `full` parser of `verifier-brief`.",
        lambda: options_table(_subparser(brief.build_parser(), "full")),
    ),
    Section(
        COMMANDS_PAGE, "brief-fixup-options", "The `fixup` parser of `verifier-brief`.",
        lambda: options_table(_subparser(brief.build_parser(), "fixup")),
    ),
    Section(COMMANDS_PAGE, "verifier-guard-commands", "The command constants of the renderer.", guard_table),
    Section(SKILL_PAGE, "verifier-guard-commands", "The command constants of the renderer.", guard_table),
    Section(COMMANDS_PAGE, "finding-codes", "The finding codes of the validator.", finding_code_table),
    Section(SKILL_PAGE, "finding-codes", "The finding codes of the validator.", finding_code_table),
    Section(DOCS_PAGE, "docs-options", "The argument parser of `delegate docs`.", lambda: options_table(build_parser())),
    Section(DOCS_PAGE, "generated-sections", "The list of sections in this module.", generated_sections_table),
)


def _block(section: Section) -> str:
    return f"<!-- generated:begin {section.id} -->\n{NOTICE}\n\n{section.build()}\n\n<!-- generated:end {section.id} -->"


def _marked(section: Section) -> re.Pattern[str]:
    return re.compile(
        rf"<!-- generated:begin {re.escape(section.id)} -->.*?<!-- generated:end {re.escape(section.id)} -->", re.DOTALL
    )


def _with_section(text: str, section: Section) -> str:
    """The page text with the section rebuilt. Raise DocsError when the page has not exactly one marked section of this id."""
    pattern = _marked(section)
    found = pattern.findall(text)
    if len(found) != 1:
        raise DocsError(
            f"{section.page}: expected one pair of markers for the section {section.id!r} "
            f"(<!-- generated:begin {section.id} --> and <!-- generated:end {section.id} -->), found {len(found)}"
        )
    return pattern.sub(lambda _: _block(section), text)


def _read(root: Path, page: str) -> str:
    path = root / page
    if not path.is_file():
        raise DocsError(f"{page}: no such page under {root}")
    return path.read_text()


def _pages(root: Path) -> dict[str, tuple[str, str]]:
    """For each page, its text now and its text with every section rebuilt. Raise DocsError for a missing page or marker."""
    pages: dict[str, tuple[str, str]] = {}
    for section in SECTIONS:
        if section.page not in pages:
            text = _read(root, section.page)
            pages[section.page] = (text, text)
        before, after = pages[section.page]
        pages[section.page] = (before, _with_section(after, section))
    return pages


def stale_sections(root: Path) -> list[Section]:
    """The sections whose text in the pages under `root` differs from the text that the code builds."""
    stale = []
    for section in SECTIONS:
        text = _read(root, section.page)
        if _with_section(text, section) != text:
            stale.append(section)
    return stale


def write_pages(root: Path) -> list[str]:
    """Rewrite every generated section under `root`. Return the pages that changed."""
    changed = []
    for page, (before, after) in _pages(root).items():
        if after != before:
            (root / page).write_text(after)
            changed.append(page)
    return changed


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="delegate docs", description="Write the generated sections of the reference pages from the code, or check that they are current."
    )
    parser.add_argument("--root", type=Path, default=Path("."), help="the repository root, which holds docs/ and skills/; default is the current directory")
    parser.add_argument("--check", action="store_true", help="write nothing; exit 1 and name each section that differs from the code")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    try:
        if args.check:
            stale = stale_sections(args.root)
            for section in stale:
                print(f"delegate docs: {section.page}: the section {section.id!r} is not current; run `delegate docs` and commit the result", file=sys.stderr)
            return 1 if stale else 0
        for page in write_pages(args.root):
            print(f"updated {page}")
    except DocsError as error:
        print(f"delegate docs: {error}", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":  # pragma: no cover
    sys.exit(main())
