"""`delegate docs`: write the generated sections of the reference pages, or check that they are current.

A page holds hand-written prose and generated sections. A generated section sits
between two markers:

    <!-- generated:begin <id> -->
    ...
    <!-- generated:end <id> -->

The command replaces the text between the markers with text that it builds from
the code (the argument parsers, the exit-code table, the renderer constants and
the finding codes), so a page cannot drift from the code. Hand-written prose
outside the markers is never touched. A section with no marker in its page is an
error, and so is a missing page: the command never adds a section to a page.
"""

from __future__ import annotations

import argparse
import re
import sys
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path

from . import run

NOTICE: str = "<!-- Generated by `delegate docs`. Do not edit this section by hand. -->"

RUN_PAGE: str = "docs/reference/run.md"


class DocsError(Exception):
    """A page is missing, or a page has no valid marker for a section. The message names the page and the section."""


@dataclass(frozen=True)
class Section:
    """One generated section: the page that holds it (relative to the root), its id, and the function that builds its text."""

    page: str
    id: str
    build: Callable[[], str]

    @property
    def name(self) -> str:
        return f"{self.page}:{self.id}"


def _value_name(action: argparse.Action) -> str:
    if action.choices:
        return "|".join(str(choice) for choice in action.choices)
    return "<" + (action.metavar or action.dest).lower().replace("_", "-") + ">"  # type: ignore[union-attr]


def _invocation(action: argparse.Action) -> str:
    """The way a reader writes the argument: `--repo <repo>`, `--dry-run`, or `[<run-id>]`."""
    if not action.option_strings:
        name = _value_name(action)
        return f"[{name}]" if action.nargs in ("?", "*") else name
    flags = ", ".join(action.option_strings)
    return flags if action.nargs == 0 else f"{flags} {_value_name(action)}"


def _sentence(text: str) -> str:
    text = text[0].upper() + text[1:]
    return text if text.endswith((".", "!", "?")) else text + "."


def options_table(parser: argparse.ArgumentParser) -> str:
    """A table of the options and the positional arguments of a parser, with the help text of each, in parser order."""
    rows = ["| Option | Meaning |", "|---|---|"]
    # `_actions` is the only way argparse lists the arguments of a parser.
    for action in parser._actions:  # noqa: SLF001
        if action.dest == "help" or isinstance(action.choices, dict):  # -h, and the action of the subcommands
            continue
        if action.help is None:
            raise DocsError(f"argument {_invocation(action)} of {parser.prog} has no help text")
        meaning = _sentence(action.help.replace("|", "\\|"))
        if action.required or (not action.option_strings and action.nargs not in ("?", "*")):
            meaning += " Required."
        rows.append(f"| `{_invocation(action)}` | {meaning} |")
    return "\n".join(rows)


SECTIONS: tuple[Section, ...] = (
    Section(RUN_PAGE, "run-options", lambda: options_table(run.build_parser())),
)


def _block(section: Section) -> str:
    return f"<!-- generated:begin {section.id} -->\n{NOTICE}\n\n{section.build()}\n\n<!-- generated:end {section.id} -->"


def _marked(section: Section) -> re.Pattern[str]:
    return re.compile(
        rf"<!-- generated:begin {re.escape(section.id)} -->.*?<!-- generated:end {re.escape(section.id)} -->", re.DOTALL
    )


def _with_section(text: str, section: Section) -> str:
    """The page text with the section rebuilt. Raise DocsError when the page has not exactly one marked section of this id."""
    pattern = _marked(section)
    found = pattern.findall(text)
    if len(found) != 1:
        raise DocsError(
            f"{section.page}: expected one pair of markers for the section {section.id!r} "
            f"(<!-- generated:begin {section.id} --> and <!-- generated:end {section.id} -->), found {len(found)}"
        )
    return pattern.sub(lambda _: _block(section), text)


def _read(root: Path, page: str) -> str:
    path = root / page
    if not path.is_file():
        raise DocsError(f"{page}: no such page under {root}")
    return path.read_text()


def _pages(root: Path) -> dict[str, tuple[str, str]]:
    """For each page, its text now and its text with every section rebuilt. Raise DocsError for a missing page or marker."""
    pages: dict[str, tuple[str, str]] = {}
    for section in SECTIONS:
        if section.page not in pages:
            text = _read(root, section.page)
            pages[section.page] = (text, text)
        before, after = pages[section.page]
        pages[section.page] = (before, _with_section(after, section))
    return pages


def stale_sections(root: Path) -> list[Section]:
    """The sections whose text in the pages under `root` differs from the text that the code builds."""
    stale = []
    for section in SECTIONS:
        text = _read(root, section.page)
        if _with_section(text, section) != text:
            stale.append(section)
    return stale


def write_pages(root: Path) -> list[str]:
    """Rewrite every generated section under `root`. Return the pages that changed."""
    changed = []
    for page, (before, after) in _pages(root).items():
        if after != before:
            (root / page).write_text(after)
            changed.append(page)
    return changed


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="delegate docs", description="Write the generated sections of the reference pages from the code, or check that they are current."
    )
    parser.add_argument("--root", type=Path, default=Path("."), help="the repository root, which holds docs/ and skills/; default is the current directory")
    parser.add_argument("--check", action="store_true", help="write nothing; exit 1 and name each section that differs from the code")
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    try:
        if args.check:
            stale = stale_sections(args.root)
            for section in stale:
                print(f"delegate docs: {section.page}: the section {section.id!r} is not current; run `delegate docs` and commit the result", file=sys.stderr)
            return 1 if stale else 0
        for page in write_pages(args.root):
            print(f"updated {page}")
    except DocsError as error:
        print(f"delegate docs: {error}", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":  # pragma: no cover
    sys.exit(main())
